---
- hosts: localhost
  become: true
  become_method: sudo
  tasks:
    - name: Install chrome via deb file
      ansible.builtin.apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
