---
- hosts: localhost
  become: true
  become_method: sudo
  tasks:
    - name: Get latest ferdium release # noqa command-instead-of-module
      ansible.builtin.shell: >
        set -o pipefail |
        curl -s -L https://api.github.com/repos/ferdium/ferdium-app/releases/latest
        | grep -Po '"tag_name": "\K.*?(?=\")' | cut -d"v" -f2
      register: ferdium_version
      changed_when: false
      failed_when: ferdium_version.rc != 0

    - name: Download and install ferdium package
      ansible.builtin.apt:
        deb: https://github.com/ferdium/ferdium-app/releases/download/v{{ ferdium_version.stdout }}/Ferdium-linux-{{ ferdium_version.stdout }}-amd64.deb
        state: present
