---
- hosts: localhost
  become: true
  become_method: sudo
  tasks:
    - name: install WakeMeOps repo and gpg key
      ansible.builtin.shell: >
        set -o pipefail |
        curl -sSL https://raw.githubusercontent.com/upciti/wakemeops/main/assets/install_repository | bash
      register: result
      changed_when: false
      failed_when: result.rc != 0
      when: packages_activate_wakemeops_repo
    - name: install a list of packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop: "{{ packages }}"
