---
- name: include vscode playbook
  ansible.builtin.import_playbook: vscode.yml
  when: install_vscode | bool

- name: include zsh playbook
  ansible.builtin.import_playbook: zsh.yml
  when: install_zsh | bool

- name: include ferdium playbook
  ansible.builtin.import_playbook: ferdium.yml
  when: install_ferdium | bool

- name: include docker playbook
  ansible.builtin.import_playbook: docker.yml
  when: install_docker | bool

- name: include packages playbook
  ansible.builtin.import_playbook: packages.yml
  when: packages is defined

- name: include spotify playbook
  ansible.builtin.import_playbook: spotify.yml
  when: install_spotify | bool
