---
- hosts: localhost
  become: true
  become_method: sudo
  tasks:
    - name: Install gpg
      ansible.builtin.apt:
        name: gpg
        state: present
        update_cache: true

    - name: Download vscode microsoft.asc
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /tmp/microsoft.asc
        mode: 0644

    - name: Extract gpg key to packages.microsoft.gpg
      ansible.builtin.shell: >
        set -o pipefail |
        /usr/bin/cat /tmp/microsoft.asc | gpg --dearmor > /tmp/packages.microsoft.gpg
      register: result
      changed_when: false
      failed_when: result.rc != 0

    - name: Import packages.microsoft.gpg to /etc/apt/keyrings/packages.microsoft.gpg
      ansible.builtin.command: >
        /usr/bin/install -D -o root -g root -m 644 /tmp/packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
      register: result
      changed_when: false
      failed_when: result.rc != 0

    - name: Create vscode repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
        filename: vscode
        state: present

    - name: Install vscode and apt-transport-https
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - apt-transport-https
        - code

    - name: Remove temporary files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/microsoft.asc
        - /tmp/packages.microsoft.gpg
